name: Releaser Binaries and WASM
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - '*'
  workflow_dispatch:

jobs:
  wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'
      
      - name: install podman
        run: sudo apt-get update && sudo apt install podman -y

      - uses: nick-fields/retry@v3
        with:
          timeout_seconds: 5
          max_attempts: 3
          command: ENGINE=podman SCRIPT_LOC=./scripts/workflows/releaser_wasm.sh ./scripts/workflows/run.sh

      - name: Prepare
          id: prepare
          run: |
              TAG=${GITHUB_REF#refs/tags/}
              echo "tag_name=${TAG}" >> $GITHUB_OUTPUT

      - name: publish binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /output/da_runtime.compact.compressed.wasm
          release_name: ${{ steps.prepare.outputs.tag_name }}
          tag: ${{ steps.prepare.outputs.tag_name }}
          overwrite: true
          file_glob: true

  wasm2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'
      
      - name: install podman
        run: sudo apt-get update && sudo apt install podman -y

      - uses: nick-fields/retry@v3
        with:
          timeout_seconds: 5
          max_attempts: 3
          command: ENGINE=podman DISTRO=ubuntu-2004 ZIP=1 ./scripts/binaries/build.sh

      - name: Prepare
          id: prepare
          run: |
              TAG=${GITHUB_REF#refs/tags/}
              echo "tag_name=${TAG}" >> $GITHUB_OUTPUT

      - name: publish binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /output/zips/x86_64-ubuntu-2004-avail-node.tar.gz
          release_name: ${{ steps.prepare.outputs.tag_name }}
          tag: ${{ steps.prepare.outputs.tag_name }}
          overwrite: true
          file_glob: true
