name: Releaser Binaries and Wasm
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - '*'
  workflow_dispatch:

jobs:
  x86_64_ubuntu_2004:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'

      - name: install podman
        run: sudo apt-get update && sudo apt install podman -y

      - name: ls
        run: ls
        
      - name: build docker image and build avail binary
        run: ENGINE=podman DISTRO=ubuntu-2004 ZIP=1 ./scripts/binaries/build.sh

      - uses: actions/upload-artifact@v2
        with:
          name: x86_64-ubuntu-2004-avail-node.tar.gz
          path: output/zips/x86_64-ubuntu-2004-avail-node.tar.gz

  # compile all binaries from previous jobs into single release
  binary_publish:
    needs: [x86_64_ubuntu_2004]
    runs-on: ubuntu-latest
    steps:
      - name: Create Artifact Directory
        run: mkdir ./artifact

      - uses: actions/download-artifact@v3
        with:
          name: x86_64-ubuntu-2004-avail-node.tar.gz
          path: ./artifact

      - name: Prepare
        id: prepare
        run: |
            TAG=${GITHUB_REF#refs/tags/}
            echo "tag_name=${TAG}" >> $GITHUB_OUTPUT

      - name: publish binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./artifact/*
          release_name: ${{ steps.prepare.outputs.tag_name }}
          tag: ${{ steps.prepare.outputs.tag_name }}
          overwrite: true
          file_glob: true
